### ISSUE TITLE
SensorML Editor Task List

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/sensorml-editor#26]
** SensorML Editor**

Features
- [ ] Add support for registering SensorML instances and models
- [x] Get ontology terms from remote ORR
- [ ] allow selection of ontologies to search
- [x] improve filtering options (e.g. search term in name only)
- [ ] Add support for emailing new term to ontology owner

General / debug
- [ ] Improve Support for Events
- [ ] Improve support for Settings and Configuration
- [ ] General Cleanup
